### ISSUE TITLE
Back arrow 

### ISSUE THREAD

**Issue by ian-hayden** [dgurns/trad-archive#67]
When using the back arrow after viewing search results the website is closed. Happens repeatedly with my Android phone but works ok using Safari on a Mac.

**Comment by dgurns** [comment]
Thanks for reporting that Ian. Just to make sure I understand -- are you talking about tapping the back arrow on this screen? (Circled in red)

![IMG_E92840CA4768-1](https://user-images.githubusercontent.com/1173791/156574577-c425188a-4051-4828-a1d3-1e2a91befb63.jpeg)

**Comment by ian-hayden** [comment]
Hi Dan

I don't have that highlighted arrow (or any of those navigation icons)
shown when using my Android phone, so I have to use the back arrow at the
top left corner. I'm a Guest, ie not logged in.

Ian

**Comment by dgurns** [comment]
Gotcha. To fix this, try clicking the "X" button on the search results to close the overlay, instead of clicking the back arrow. That should hopefully solve the problem.
